### ISSUE TITLE
Getting a struct error: "struct.error: ushort format requires 0 <= number <= USHRT_MAX"

### ISSUE THREAD

**Issue by Sithari** [earthquake/XFLTReaT#5]
Hello, I am trying to get the code running to test the DNS exfil capabilities. Unfortunately I am getting the following error when running the code:
struct.error: ushort format requires 0 <= number <= USHRT_MAX

Can someone help me figure what I need to do to get around this or fix this? I am using an ec2 instance in AWS along with a .tk domain if that helps. Using v0.2.

Entire stacktrace is below:
```
fizz@fizz-VirtualBox:~/Downloads/XFLTReaT$ sudo python xfltreat.py --client --verbose 2

,--.   ,--.,------.,--.,--------.,------.                ,--------. 
 \  `.'  / |  .---'|  |'--.  .--'|  .--. ' ,---.  ,--,--.'--.  .--' 
  .'    \  |  `--, |  |   |  |   |  '--'.'| .-. :' ,-.  |   |  |    
 /  .'.  \ |  |`   |  '--.|  |   |  |\  \ \   --.\ '-'  |   |  |    
'--'   '--'`--'    `-----'`--'   `--' '--' `----' `--`--'   `--'    
Balazs Bucsay [[@xoreipeip]]

[*] Parsing config file
[*] Loading all modules from 'modules' directory
[*] Setting up interface
[*] Changing route table for intermediate hop
[*] Using nameserver: 8.8.8.8
[*] Starting client: DNS
[*] Sending request u-r: A d-r: CNAME u-e: Base32 d-e: Base32 u-l: 0 d-l: 30
[+] Request succeed: u-r: A d-r: CNAME u-e: Base32 d-e: Base32 u-l: 0 d-l: 30
[+] A record can be used for upstream.
[*] Sending request u-r: A d-r: CNAME u-e: Base32 d-e: Base32 u-l: 50 d-l: 10
[-] Request for A record with Base32 encoding failed: integrity error
[*] Sending request u-r: A d-r: CNAME u-e: Base64 DNS d-e: Base64 DNS u-l: 50 d-l: 10
[-] Request for A record with Base64 DNS encoding failed: integrity error
[+] Record 'A' with Base32 encoding found to be the best for upstream.
[*] Sending request u-r: A d-r: CNAME u-e: Base32 d-e: Base32 u-l: 255 d-l: 0
[-] DEBUG: Query error: Format error - the DNS server does not support this format (maybe the query was too long)
[*] Sending request u-r: A d-r: CNAME u-e: Base32 d-e: Base32 u-l: 127 d-l: 0
[-] Request for 'A' record with 'Base32' encoding failed: integrity error
[*] Sending request u-r: A d-r: CNAME u-e: Base32 d-e: Base32 u-l: 63 d-l: 0
[-] Request for 'A' record with 'Base32' encoding failed: integrity error
[*] Sending request u-r: A d-r: CNAME u-e: Base32 d-e: Base32 u-l: 31 d-l: 0
[-] Request for 'A' record with 'Base32' encoding failed: integrity error
[*] Sending request u-r: A d-r: CNAME u-e: Base32 d-e: Base32 u-l: 15 d-l: 0
[-] Request for 'A' record with 'Base32' encoding failed: integrity error
[*] Sending request u-r: A d-r: CNAME u-e: Base32 d-e: Base32 u-l: 7 d-l: 0
[-] Request for 'A' record with 'Base32' encoding failed: integrity error
[*] Sending request u-r: A d-r: CNAME u-e: Base32 d-e: Base32 u-l: 3 d-l: 0
[-] Request for 'A' record with 'Base32' encoding failed: integrity error
[*] Sending request u-r: A d-r: CNAME u-e: Base32 d-e: Base32 u-l: 1 d-l: 0
[-] Request for 'A' record with 'Base32' encoding failed: integrity error
[+] Record 'A' with 'Base32' encoding can be used with maximum length of 188
[*] Sending request u-r: A d-r: NULL u-e: Base32 d-e: Base32 u-l: 0 d-l: 50
[-] Request for 'A' record with 'Base32' encoding failed: wrong length
[*] Sending request u-r: A d-r: PRIVATE u-e: Base32 d-e: Base32 u-l: 0 d-l: 50
[-] Request for 'A' record with 'Base32' encoding failed: wrong length
[*] Sending request u-r: A d-r: CNAME u-e: Base32 d-e: Base32 u-l: 0 d-l: 50
[-] Request for 'A' record with 'Base32' encoding failed: wrong length
[+] Record 'NULL' can be used for downstream.
[*] Sending request u-r: A d-r: NULL u-e: Base32 d-e: Base32 u-l: 50 d-l: 50
[-] Request for 'A' record with 'Base32' encoding failed: wrong length
[*] Sending request u-r: A d-r: NULL u-e: Base32 d-e: Base64 DNS u-l: 50 d-l: 50
[-] Request for 'A' record with 'Base32' encoding failed: wrong length
[*] Sending request u-r: A d-r: NULL u-e: Base32 d-e: Plaintext u-l: 50 d-l: 50
[-] Request for 'A' record with 'Base32' encoding failed: wrong length
[+] Record 'NULL' can be used with encoding 'Base32' for downstream.
[*] Sending request u-r: A d-r: NULL u-e: Base32 d-e: Base32 u-l: 188 d-l: 800
[-] Request for 'A' record with 'Base32' encoding failed: wrong length
[*] Sending request u-r: A d-r: NULL u-e: Base32 d-e: Base32 u-l: 188 d-l: 400
[-] Request for 'A' record with 'Base32' encoding failed: wrong length
[*] Sending request u-r: A d-r: NULL u-e: Base32 d-e: Base32 u-l: 188 d-l: 200
[-] Request for 'A' record with 'Base32' encoding failed: wrong length
[*] Sending request u-r: A d-r: NULL u-e: Base32 d-e: Base32 u-l: 188 d-l: 100
[-] Request for 'A' record with 'Base32' encoding failed: wrong length
[*] Sending request u-r: A d-r: NULL u-e: Base32 d-e: Base32 u-l: 188 d-l: 50
[-] Request for 'A' record with 'Base32' encoding failed: wrong length
[*] Sending request u-r: A d-r: NULL u-e: Base32 d-e: Base32 u-l: 188 d-l: 25
[-] Request for 'A' record with 'Base32' encoding failed: wrong length
[*] Sending request u-r: A d-r: NULL u-e: Base32 d-e: Base32 u-l: 188 d-l: 12
[*] Restoring default route
Traceback (most recent call last):
  File "xfltreat.py", line 308, in <module>
    xfltreat.run(sys.argv[1:])
  File "xfltreat.py", line 263, in run
    m.connect()
  File "/home/fizz/Downloads/XFLTReaT/modules/DNS.py", line 1051, in connect
    if self.do_autotune(server_socket):
  File "/home/fizz/Downloads/XFLTReaT/modules/DNS.py", line 479, in do_autotune
    message = struct.pack("<BHHH", 0, self.DNS_proto.reverse_RR_type_num(download_record_type), length_new, download_encoding)
struct.error: ushort format requires 0 <= number <= USHRT_MAX
```

**Comment by earthquake** [comment]
Hi Sithari,

Google has some DNS tunnelling protection in their servers so it is not going to work properly ever. Please use the latest versions with other DNS servers instead of v0.2. Let me know if it still broken.
